spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportwear_shop?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
    username: root
    password: "abc123!@#"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: sportwearshopvn@gmail.com
    password: kvcz wmrg iqeh voxy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: "mot_secret_dai_hon_32_ky_tu_cho_local_dev_123456"
  access-expiration: 3600000
  refresh-expiration: 604800000

app:
  upload:
    dir: D:/NguyenHuuQuan_DATN/sportwear-shop-ai/backend/uploads

  auth:
    verification-code-expiration-minutes: 10
    reset-password-code-expiration-minutes: 10

  payment:
    bank-qr:
      bank-name: Vietcombank
      account-number: 0010000000355
      account-holder: Nguyen Huu Quan
      qr-expire-minutes: 1
      payment-code-prefix: SW
      sepay:
        webhook-token: CHANGE_ME_SEPAY_WEBHOOK_TOKEN

  ai:
    enabled: true
    max-history: 6
    gemini:
      api-key: ${GEMINI_API_KEY:}
      model: gemini-2.0-flash-lite
      url: https://generativelanguage.googleapis.com/v1beta/models

