spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportwear_shop?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
    username: root
    password: abc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: quan2807_local_dev_secret_key_2026_super_long_x9k2
  access-expiration: 3600000
  refresh-expiration: 604800000

app:
  upload:
    dir: D:/NguyenHuuQuan_DATN/sportwear-shop-ai/backend/uploads